apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: insightserenity

resources:
  - namespace.yaml
  - api-gateway.yaml
  - ai-engine.yaml
  - postgres.yaml
  - redis.yaml

commonLabels:
  app.kubernetes.io/part-of: insightserenity
